#!/bin/bash
# this will launch dde-launcher

dbus-send --print-reply --session --dest=org.desktopspec.ApplicationManager /org/desktopspec/ApplicationManager org.desktopspec.ApplicationManager.Launch string:/usr/share/applications/dde-launcher.desktop
