/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a dbuslauncherservice -c DBusLauncherService -l DBusLauncherService com.deepin.dde.Launcher.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUSLAUNCHERSERVICE_H_1458107102
#define DBUSLAUNCHERSERVICE_H_1458107102

#include "../mainframe.h"

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.dde.Launcher
 */
class DBusLauncherService: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.dde.Launcher")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.dde.Launcher\">\n"
"    <method name=\"Exit\"/>\n"
"    <method name=\"Show\"/>\n"
"    <method name=\"Hide\"/>\n"
"    <method name=\"Toggle\"/>\n"
"    <method name=\"ShowByMode\">\n"
"      <arg direction=\"in\" type=\"x\"/>\n"
"    </method>\n"
"    <method name=\"UninstallApp\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"    <signal name=\"Closed\"/>\n"
"    <signal name=\"Shown\"/>\n"
"  </interface>\n"
        "")
public:
    explicit DBusLauncherService(MainFrame *parent);
    virtual ~DBusLauncherService();

    inline MainFrame *parent() const
    { return static_cast<MainFrame *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void Exit();
    void Hide();
    void Show();
    void ShowByMode(qlonglong in0);
    void UninstallApp(const QString &appKey);
    void Toggle();
Q_SIGNALS: // SIGNALS
    void Closed();
    void Shown();
};

#endif
