/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p dock_interface.h:dock_interface.cpp -c DockInterface ./dock.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DOCK_INTERFACE_H_1449473752
#define DOCK_INTERFACE_H_1449473752

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.deepin.dde.dock
 */
class DockInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.deepin.dde.dock"; }

public:
    DockInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~DockInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<qulonglong> Xid()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Xid"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

#endif
