/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p dde_launchersettings_interface.h:dde_launchdersettings_interface.cpp -c LauncherSettingsInterface launchersettings.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DDE_LAUNCHERSETTINGS_INTERFACE_H_1441019133
#define DDE_LAUNCHERSETTINGS_INTERFACE_H_1441019133

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.deepin.dde.daemon.launcher.Setting
 */
class LauncherSettingsInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.deepin.dde.daemon.launcher.Setting"; }

public:
    LauncherSettingsInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~LauncherSettingsInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<qlonglong> GetCategoryDisplayMode()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("GetCategoryDisplayMode"), argumentList);
    }

    inline QDBusPendingReply<qlonglong> GetSortMethod()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("GetSortMethod"), argumentList);
    }

    inline QDBusPendingReply<> SetCategoryDisplayMode(qlonglong in0)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0);
        return asyncCallWithArgumentList(QStringLiteral("SetCategoryDisplayMode"), argumentList);
    }

    inline QDBusPendingReply<> SetSortMethod(qlonglong in0)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0);
        return asyncCallWithArgumentList(QStringLiteral("SetSortMethod"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void CategoryDisplayModeChanged(qlonglong in0);
    void SortMethodChanged(qlonglong in0);
};

#endif
